# deprecated configuration file for diagnostics (archived 2020)

diagnostics:
  retry: 3
  timeout: 15
  enable_logging: true
  output_dir: /var/log/rtc-tracer/
  legacy_option_0: true
  legacy_option_1: true
  legacy_option_2: true
  legacy_option_3: true
  legacy_option_4: true
  legacy_option_5: true
  legacy_option_6: true
  legacy_option_7: true
  legacy_option_8: true
  legacy_option_9: true
  legacy_option_10: true
  legacy_option_11: true
  legacy_option_12: true
  legacy_option_13: true
  legacy_option_14: true
  legacy_option_15: true
  legacy_option_16: true
  legacy_option_17: true
  legacy_option_18: true
  legacy_option_19: true
  legacy_option_20: true
  legacy_option_21: true
  legacy_option_22: true
  legacy_option_23: true
  legacy_option_24: true
  legacy_option_25: true
  legacy_option_26: true
  legacy_option_27: true
  legacy_option_28: true
  legacy_option_29: true
  legacy_option_30: true
  legacy_option_31: true
  legacy_option_32: true
  legacy_option_33: true
  legacy_option_34: true
  legacy_option_35: true
  legacy_option_36: true
  legacy_option_37: true
  legacy_option_38: true
  legacy_option_39: true
  legacy_option_40: true
  legacy_option_41: true
  legacy_option_42: true
  legacy_option_43: true
  legacy_option_44: true
  legacy_option_45: true
  legacy_option_46: true
  legacy_option_47: true
  legacy_option_48: true
  legacy_option_49: true

reporting:
  include_metadata: false
  compress_output: true
  custom_tag_0: v0.x-testing
  custom_tag_1: v1.x-testing
  custom_tag_2: v2.x-testing
  custom_tag_3: v3.x-testing
  custom_tag_4: v4.x-testing
  custom_tag_5: v5.x-testing
  custom_tag_6: v6.x-testing
  custom_tag_7: v7.x-testing
  custom_tag_8: v8.x-testing
  custom_tag_9: v9.x-testing
  custom_tag_10: v10.x-testing
  custom_tag_11: v11.x-testing
  custom_tag_12: v12.x-testing
  custom_tag_13: v13.x-testing
  custom_tag_14: v14.x-testing
  custom_tag_15: v15.x-testing
  custom_tag_16: v16.x-testing
  custom_tag_17: v17.x-testing
  custom_tag_18: v18.x-testing
  custom_tag_19: v19.x-testing
  custom_tag_20: v20.x-testing
  custom_tag_21: v21.x-testing
  custom_tag_22: v22.x-testing
  custom_tag_23: v23.x-testing
  custom_tag_24: v24.x-testing
  custom_tag_25: v25.x-testing
  custom_tag_26: v26.x-testing
  custom_tag_27: v27.x-testing
  custom_tag_28: v28.x-testing
  custom_tag_29: v29.x-testing